# Pre-commit hooks
# Install before first use with: 'pre-commit install'
- repo: local
  hooks:
  # modernizer: make sure our code-base is Python 3 ready
  # Doesn't modify the code, just checks
  - id: python-modernize
    name: python-modernize
    entry: python-modernize
    language: system
    exclude: &exclude_files >
      (?x)^(
        docs/.*|
        examples/.*|
      )$
    args: ["--enforce"]

  # yapf = yet another python formatter
  - id: yapf
    name: yapf
    entry: yapf
    language: system
    types: [python]
    args: ["-i"]
    exclude: *exclude_files

  # prospector: collection of linters
  - id: prospector
    language: system
    types: [file, python]
    name: prospector
    description: "This hook runs Prospector: https://github.com/landscapeio/prospector"
    entry: prospector
    exclude: *exclude_files

